### ISSUE TITLE
Create reusable components

### ISSUE THREAD

**Issue by lucymk** [fac-12/Albert-Kennedy#28]
- [x] button
- [x] header

**Comment by sophielevens** [comment]
Hey Tom, 
Can you send over the set of AKT logos so we can use them within the app?

**Comment by hellotomjohnson** [comment]
@sophielevens Sure thing. See attached. Let me know if you need anything else.
[Logos.zip](https://github.com/fac-12/Albert-Kennedy/files/1695913/Logos.zip)

**Comment by sophielevens** [comment]
@hellotomjohnson 🐇 💨  thanks so much for the speedy response!

**Comment by hannahcmtucker** [comment]
done :)
