### ISSUE TITLE
Form fields

### ISSUE THREAD

**Issue by lucymk** [fac-12/Albert-Kennedy#75]
Add to registration form inputs for ethnicity (census ethnicity with dropdown)

**Comment by lucymk** [comment]
We spoke about making the extra information request on a subsequent page from the basic user info, with a little bit of text explaining why it's necessary (to be provided by @hellotomjohnson). We should talk about this design choice with @nogainbar

**Comment by sophielevens** [comment]
@hellotomjohnson could you please provide us with a list of the ethnicity categories you would like us to include within the form?

**Comment by hellotomjohnson** [comment]
@sophielevens here's what we need to capture re ethnicity. do you think this will work? if not, we could just add another open field. i'll let you decide what's best. thanks!

Asian - Bangladeshi
Asian - British
Asian - Chinese
Asian - Indian
Asian - Pakistani
Black - African
Black - British
Black - Caribbean
Mixed/Multiple - White and Asian
Mixed/Multiple - White and Black African
Mixed/Multiple - White and Black Caribbean
White - British
White - Irish
Arab
Traveller - Irish Traveller
Traveller - Romany/Gyspy
Prefer not to say
Other (please specify)
