### ISSUE TITLE
Storing and using user data

### ISSUE THREAD

**Issue by lucymk** [fac-12/Albert-Kennedy#76]
Currently, not all user data is being stored, and it's not being sent to AKT either. We should 

- [x] store the relevant info in the database 
- [x] research extracting database info in CSV format for easier access for AKT staff

**Comment by sophielevens** [comment]
https://stackoverflow.com/questions/17463299/export-database-into-csv-file

https://stackoverflow.com/questions/1517635/save-pl-pgsql-output-from-postgresql-to-a-csv-file

http://www.postgresqltutorial.com/export-postgresql-table-to-csv-file/

<img width="772" alt="screen shot 2018-04-23 at 17 05 43" src="https://user-images.githubusercontent.com/25961258/39138880-a69387fe-4718-11e8-9872-064f19069a20.png">
