### ISSUE TITLE
TOM IS THE BEST P.O.! 🎉

### ISSUE THREAD

**Issue by lucymk** [fac-12/Albert-Kennedy#87]
@hellotomjohnson prioritising already, you're so efficient! 😄🌟

**Comment by hellotomjohnson** [comment]
@lucymk [smug emoji] there weren't enough priority numbers for each specific issue, so i've grouped them, just to give you a sense of importance. i've left those other things at the bottom, because i assume you'll be working on these anyway...!

**Comment by lucymk** [comment]
@hellotomjohnson sorry I should have explained better, but that's exactly what you're supposed to do! and yes we certainly will, we can decide on their priority and put them in 😀 thanks so much and have a great evening!
