### ISSUE TITLE
Design resources

### ISSUE THREAD

**Issue by sophielevens** [fac-12/Albert-Kennedy#88]
Hi @hellotomjohnson, we have a designer looking at options for the desktop design today and wondered if you have some suitable images you could share with us? 

As the design is going to be larger, we were thinking of including some images to utilise the extra space.

We were also wondering if you can supply us with the DIM font file which you have listed in the AKT style guide pdf. 

Thanks!

**Comment by sophielevens** [comment]
Also, do you have access to the logo that you used for interAKT? (see below)
Perhaps without the "The Albert Kennedy Trust" on there

![interakt logo](https://user-images.githubusercontent.com/25961258/39183384-b21cd7d4-47b7-11e8-87fb-d48312c6f970.png)

Thanks ! ✨

**Comment by hellotomjohnson** [comment]
@sophielevens hi sophie, i've had a chat with colleagues and we'd still like to stick with patterned backgrounds over images. we used this site for our website backgrounds - https://www.heropatterns.com/ - so might be worth designing the background using this, using our corporate colour purple along with some complimentary and more vibrant colours. what do you think? what are the options you have?

we don't have a logo that doesn't have the albert kennedy trust underneath inter-akt, unfortunately.

**Comment by sophielevens** [comment]
Hey @hellotomjohnson, could you please provide the logo with the text underneath it? That will work for us. 

Here is an example of the font that we are currently using, would you like to continue with this or to send us the DIN font we spoke about this morning?

<img width="791" alt="screen shot 2018-04-27 at 12 03 54" src="https://user-images.githubusercontent.com/25961258/39360062-86230f4a-4a14-11e8-9da4-45d83bf71c2d.png">

**Comment by sophielevens** [comment]
@hellotomjohnson, here are some initial designs that we've been playing around with, the images are just stock photos from unsplash.com. With the purple filters over images we're keeping more continuity with the AKT website and bringing life to the desktop designs to inspire more young people to use the app and engage with it (we've also included some in the mobile designs too!)

As you can see below, I have included some examples of the new designs alongside the old ones so you can make an informed decision. However, if you and your team would be happier for us to not include the images then that is also fine with us 😄please let us know what you think, as soon as you do we can move forward with this  👍 

<img width="308" alt="screen shot 2018-04-18 at 12 59 51" src="https://user-images.githubusercontent.com/25961258/39361348-ee45543e-4a19-11e8-9aeb-8b0e207fd35d.png">


<img width="402" alt="screen shot 2018-04-27 at 12 35 41" src="https://user-images.githubusercontent.com/25961258/39360970-4d29e87c-4a18-11e8-90e9-e6f93698b95e.png">


<img width="1279" alt="screen shot 2018-04-27 at 10 15 33" src="https://user-images.githubusercontent.com/25961258/39360971-4e180d54-4a18-11e8-93cd-e2cbb1d66db1.png">

<img width="1274" alt="screen shot 2018-04-27 at 12 31 13" src="https://user-images.githubusercontent.com/25961258/39361279-9b29b3f8-4a19-11e8-8e27-874786a038c6.png">

**Comment by hellotomjohnson** [comment]
thanks @sophielevens. let's just go for the block purple with squiggle you've put at the end of your message, so no people, no gradient, just simple. the white box keeps it clean and accessible too.  the font you're using is absolutely fine. our server has been down all day so I can't get any files to you right now.  i'll make a note to do this on monday morning. If there's anything I can help with over github for the next hour, just shout.

**Comment by hellotomjohnson** [comment]
@sophielevens  in addition to the purple logo you shared above, see these inter-akt files in case they are of use.
[interAKT.zip](https://github.com/fac-12/Albert-Kennedy/files/1963561/interAKT.zip)
